subreddits:
  - history
  - science
  - politics

analyser_config:
  K_vals: [5, 11, 17, 23]
  test_size: 0.2
  cross_val: 5
  C_vals: [0.001, 0.01, 0.1, 0.5, 1]
  lasso_alpha: 1
  positive_reaction: 2
  dummy_strategy: "most_frequent"

submission_limit:
  50

meaningless_chars:
  "1234567890`¬-=_+[]{};'#:@~,./<>?\\|!\"£$%^&*()"

data_dir:
  data

data_file_name:
  big.pickle

debug:
  true
