subreddits:
  - history

analyser_config:
  K_val: 15
  test_size: 0.3
  cross_val: 5
  L_val: 1
  lasso_alpha: 1
  dummy_strategy: "most_frequent"

submission_limit:
  30

meaningless_chars:
  "1234567890`¬-=_+[]{};'#:@~,./<>?\\|!\"£$%^&*()"

data_dir:
  data

data_file_name:
  big.pickle

debug:
  true
